version: '3'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api
    ports:
      - 5432:5432
